name = "VSL"
uuid = "04294c92-b9b2-5258-861c-e23397c8ec5d"
author = ["Sunoru <s@sunoru.com>"]
repo = "https://github.com/JuliaRandom/VSL.jl.git"
version = "0.2.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Printf", "Test"]

[compat]
julia = "1"
